"""
Django settings for locallibrary project.

Generated by 'djago-admin startproject' using Django 1.11

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
"""

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECURITY_KEY = '' # Secret Key

# DEBUG = False

ALLOWED_HOSTS = ['']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends,sqlite3'
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
  
    'musicbrainz': {
    'ENGINE': 'django.db.backends.postgresql_psycopg2' # sudo pip install psycopg2
    'NAME': 'musicbrainz_db',
    'USER': 'musicbrainz',
    'PASSWORD': '',
            'HOST': '127.0.0.1',
    'PORT': '5432',
    }
}

DATABASE_ROUTERS = ['django_musicbrainz.router.MusicbrainzRouter',]
